# Generated by Django 4.2.14 on 2025-07-26 16:37

from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Wallet",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "label",
                    models.CharField(
                        help_text="A unique label for the wallet.",
                        max_length=255,
                        unique=True,
                    ),
                ),
                (
                    "balance",
                    models.DecimalField(
                        decimal_places=18,
                        default=Decimal("0.00"),
                        help_text="Current balance of the wallet, sum of all transactions. Cannot be negative.",
                        max_digits=30,
                    ),
                ),
            ],
            options={
                "verbose_name": "Wallet",
                "verbose_name_plural": "Wallets",
                "ordering": ["label"],
                "indexes": [
                    models.Index(fields=["label"], name="api_wallet_label_612641_idx")
                ],
            },
        ),
        migrations.CreateModel(
            name="Transaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "txid",
                    models.CharField(
                        db_index=True,
                        help_text="Unique external transaction identifier.",
                        max_length=255,
                        unique=True,
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=18,
                        help_text="The amount of the transaction. Can be positive (deposit) or negative (withdrawal).",
                        max_digits=30,
                    ),
                ),
                (
                    "timestamp",
                    models.DateTimeField(
                        auto_now_add=True, help_text="Timestamp of the transaction."
                    ),
                ),
                (
                    "wallet",
                    models.ForeignKey(
                        help_text="The wallet associated with this transaction.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="transactions",
                        to="api.wallet",
                    ),
                ),
            ],
            options={
                "verbose_name": "Transaction",
                "verbose_name_plural": "Transactions",
                "ordering": ["wallet", "-timestamp"],
                "indexes": [
                    models.Index(
                        fields=["wallet"], name="api_transac_wallet__280e1b_idx"
                    )
                ],
            },
        ),
    ]
